# stage build
FROM node:18-alpine

WORKDIR /app

# copy everything to the container
COPY . .

RUN npm install -g pnpm@latest-10

# clean install all dependencies
RUN pnpm install

# build SvelteKit app
RUN pnpm run build


# stage run
FROM node:18-alpine

WORKDIR /app

# copy dependency list
COPY --from=0 /app/package.json ./

# copy built SvelteKit app to /app
COPY --from=0 /app/build ./

ENV PORT 8080
EXPOSE 8080
CMD ["node", "./index.js"]